[pytest]
pythonpath = .
filterwarnings =
    ignore:The default value of `allowed_objects` will change.*:langchain_core._api.deprecation.LangChainPendingDeprecationWarning
    ignore:The anyio.abc.BlockingPortal alias is deprecated.*:DeprecationWarning
